import type { UiLanguage } from "@/types";

// 앱 UI 언어는 콘텐츠 언어와 별개이고 기본값은 베트남어다. (DESIGN.md 26번 항목)
// DESIGN.md의 화면 목업 문구(한국어)는 ko에 그대로 옮겨 팀 QA에 쓴다.
const vi = {
  studioLabel: "One product. One maker. One story.",
  uploadIntro: "Từ ảnh và lời kể của bạn, tạo nội dung, kiểm tra rồi chia sẻ câu chuyện tác phẩm qua mã QR.",
  photoStep: "Ảnh", verifyStep: "Xác nhận", storyStep: "Câu chuyện", resultStep: "Nội dung",
  photoTitle: "Bắt đầu với một tác phẩm",
  photoBody: "Chọn một ảnh rõ nét, nền đơn giản và thấy trọn hình dáng cùng hoa văn.",
  photoTips: "Một tác phẩm · Đủ ánh sáng · Không dùng bộ lọc",
  uploadNext: "Tiếp theo: xem và sửa những đặc điểm AI nhận diện.",
  uploadingImage: "Đang tải ảnh lên…",
  verifyIntro: "Đây là gợi ý từ ảnh, chưa phải kết luận. So sánh với tác phẩm và sửa những điểm chưa đúng bên dưới.",
  patternIntro: "AI chỉ đề xuất theo hình dáng nhìn thấy. Chọn hoa văn bạn nhận ra; nếu chưa chắc, chọn “Không xác định / không có”.",
  storyIntro: "Kể về cảm hứng, một kỷ niệm hoặc chi tiết bạn muốn người mua hiểu. AI chỉ biên tập những điều bạn cung cấp.",
  storyHelp: "Có thể bỏ trống. Khi đó, nội dung chỉ mô tả các đặc điểm đã xác nhận, không tạo câu chuyện thay bạn.",
  storyPrompt: "Điều gì khiến bạn muốn làm tác phẩm này?",
  resultHelp: "Giới thiệu: tên và mô tả để bán hàng. Câu chuyện: lời kể của bạn được biên tập. SNS: bài đăng ngắn. Chọn ngôn ngữ rồi sao chép phần cần dùng.",

  typeHelp: "Chọn theo hình dáng thực tế. Nếu ảnh chưa rõ, giữ “Không xác định”.",
  colorHelp: "Chọn tối đa 3 màu trên sản phẩm, không tính nền và bóng đổ.",
  featureHelp: "Nhấn × để bỏ đặc điểm không đúng. Ảnh không xác nhận được chất liệu hay kỹ thuật chế tác.",
  productHelp: "Tên dùng cho tiêu đề sản phẩm; mô tả ngắn dùng trên nhãn; mô tả đầy đủ dùng trên trang bán hàng.",
  socialHelp: "Bài đăng ngắn để giới thiệu trên Facebook hoặc Instagram. Kiểm tra lại thông tin trước khi đăng.",
  storyResultHelp: "So sánh bản gốc với bản biên tập. Cảm hứng và trải nghiệm phải đúng với lời bạn kể.",
  cultureHelp: "Thông tin tham khảo về hoa văn đã chọn; không xác nhận nguồn gốc hay niên đại của tác phẩm.",
  observationsTitle: "AI quan sát từ ảnh",
  referencesTitle: "Tài liệu tham khảo có nguồn",
  noReference: "Chưa có tài liệu tham khảo có nguồn.",
  descriptionLabel: "Mô tả hoa văn", originLabel: "Bối cảnh lịch sử", worksLabel: "Tác phẩm tham khảo",
  shapeLabel: "Hình dáng", surfaceLabel: "Bề mặt và men", layoutLabel: "Vị trí trang trí", elementsLabel: "Chi tiết trang trí", compositionLabel: "Bố cục",
  observationLimit: "Chỉ mô tả những gì nhìn thấy. Không xác định niên đại, lò gốm, xuất xứ hay tính xác thực. ‘not visible’ nghĩa là không quan sát được từ ảnh. Có thể xem nội dung quan sát bằng tiếng Hàn, tiếng Việt hoặc tiếng Anh.",
  confidenceLow: "AI dự đoán · Độ tin cậy thấp",
  back: "Quay lại",

  uploadHeading: "Mỗi tác phẩm,\nmột câu chuyện.",
  uploadHint: "Chụp ở nơi sáng, thấy rõ toàn bộ sản phẩm.",
  takePhoto: "Chụp ảnh",
  chooseFromGallery: "Chọn từ thư viện",
  retakePhoto: "Chụp lại",
  changePhoto: "Đổi ảnh",
  startAnalysis: "Bắt đầu phân tích",
  supportedFormats: "JPG · PNG · WEBP / HEIC tùy trình duyệt",
  unsupportedType: "Chỉ dùng được ảnh JPG, PNG, WEBP hoặc HEIC.",
  imageDecodeFailed: "Không đọc được ảnh này. Hãy thử ảnh khác.",
  preparingImage: "Đang chuẩn bị ảnh...",
  uiLanguageToggle: "한국어",

  analyzingTitle: "Đang xem tác phẩm của bạn.",
  analyzingBody:
    "Đang phân tích loại sản phẩm, màu sắc, đặc điểm nhìn thấy và hoa văn.",
  analyzeFailed: "Không thể phân tích ảnh.",
  chooseAnotherPhoto: "Chọn ảnh khác",

  observationHeading: "Kết quả phân tích",
  productType: "Loại sản phẩm",
  mainColors: "Màu chính",
  addColor: "+ Thêm màu",
  visualFeatures: "Đặc điểm nhìn thấy",
  removeItem: "Bỏ",
  noFeatures: "Không có đặc điểm nào được chọn.",

  patternHeading: "Đây là hoa văn gì?",
  patternSelectHint: "Hãy chọn một hoa văn.",
  noPattern: "Không xác định / không có",
  confidenceHigh: "Ứng viên khá giống",
  confidenceMedium: "Có thể giống",
  allLowTitle: "Không tìm thấy hoa văn nào đủ chắc chắn.",
  noCandidatesTitle: "AI không tìm thấy hoa văn phù hợp trong danh sách đã đăng ký.",
  showAllPatterns: "Xem tất cả hoa văn",
  patternDetail: "Chi tiết",
  patternMeaningTitle: "Ý nghĩa văn hóa",
  patternNoCulture: "Chưa có thông tin văn hóa đã được kiểm chứng.",
  patternSource: "Nguồn",
  close: "Đóng",
  continueConfirmed: "Xác nhận và tiếp tục",
  freeInputNotice:
    "Chỉ chọn được hoa văn trong danh sách đã kiểm chứng. Nếu không có, hãy chọn “Không xác định / không có”.",

  storyHeading: "Hãy kể về tác phẩm này.",
  storyTabText: "Tự nhập",
  storyTabVoice: "Nói bằng giọng nói",
  storyPlaceholder:
    "Ví dụ: “Tôi làm tác phẩm này khi nhớ về những bông sen trong ao làng hồi nhỏ.”",
  storyTooLong: "Đã vượt quá 1000 ký tự.",
  createContent: "Tạo nội dung",
  recordStart: "Bắt đầu ghi âm",
  recordMax: "Tối đa 60 giây",
  recording: "Đang ghi âm",
  recordStop: "Dừng ghi âm",
  transcribing: "Đang chuyển giọng nói thành văn bản.",
  sttHeard: "AI nghe được như sau.",
  recordAgain: "Ghi âm lại",
  useThisText: "Dùng nội dung này",
  appendAfter: "Thêm vào cuối",
  replaceExisting: "Thay nội dung cũ",
  cancel: "Hủy",
  micError: "Trình duyệt này có thể hạn chế ghi âm.",
  micHelp: "Hãy mở trang bằng Chrome hoặc Safari thay vì trình duyệt trong ứng dụng.",
  micHelpButton: "Cách mở trong trình duyệt",
  typeInstead: "Tự nhập",
  sttFailed: "Không nhận dạng được giọng nói.",
  voiceOptional: "Ghi âm là tùy chọn. Chỉ cần tự nhập cũng tạo được nội dung.",

  resultNoticeTitle: "Lời giới thiệu đã sẵn sàng.",
  resultNoticeBody:
    "Đây là nội dung do AI sắp xếp. Hãy kiểm tra thông tin và cách diễn đạt trước khi sao chép.",
  tabProduct: "Giới thiệu",
  tabStory: "Câu chuyện",
  tabCulture: "Văn hóa",
  tabSocial: "SNS",
  storyOriginal: "Nguyên văn của nghệ nhân",
  storyPolished: "Câu chuyện do AI sắp xếp",
  storyEmpty: "Nghệ nhân chưa nhập câu chuyện.",
  cultureFromDb: "Nội dung được ghi trong Pattern Database.",
  copy: "Sao chép",
  copyAll: "Sao chép tất cả",
  copied: "✓ Đã sao chép",
  copyFailed: "Không thể tự động sao chép. Hãy nhấn giữ vào văn bản để sao chép.",
  generating: "Đang sắp xếp câu chuyện của tác phẩm.",
  generateFailed: "Đã xảy ra sự cố khi tạo nội dung.",
  retry: "Thử lại",
  editPattern: "Sửa hoa văn",
  editStory: "Sửa câu chuyện",
  regenerate: "Tạo lại",
  apiKeyMissing: "Dịch vụ AI chưa sẵn sàng. Hãy thử lại sau hoặc liên hệ người quản lý.",
};

export type CopyDict = typeof vi;

const ko: CopyDict = {
  studioLabel: "One product. One maker. One story.",
  uploadIntro: "작품 사진과 장인의 목소리로 소개를 만들고, 직접 확인한 이야기를 QR로 전하세요.",
  photoStep: "사진", verifyStep: "확인", storyStep: "이야기", resultStep: "완성",
  photoTitle: "작품 한 점으로 시작해요",
  photoBody: "단순한 배경에서 형태와 문양이 모두 보이는 선명한 사진을 골라주세요.",
  photoTips: "작품 한 점 · 밝은 조명 · 필터 없이",
  uploadNext: "다음 단계에서 AI가 찾은 특징을 확인하고 수정해요.",
  uploadingImage: "사진을 올리는 중…",
  verifyIntro: "AI가 사진에서 찾은 특징이에요. 실제 작품과 비교하고, 틀린 부분을 아래에서 수정해주세요.",
  patternIntro: "AI는 보이는 형태로만 문양을 제안해요. 직접 확인한 문양을 선택하고, 확실하지 않으면 ‘없음 / 알 수 없음’을 골라주세요.",
  storyIntro: "만들게 된 계기, 떠오르는 기억, 구매자에게 전하고 싶은 디테일을 적어주세요. AI는 알려주신 내용 안에서만 문장을 다듬어요.",
  storyHelp: "비워두어도 괜찮아요. 이야기가 없으면 확인한 특징으로만 소개를 만들고, 작가의 경험이나 의도는 지어내지 않아요.",
  storyPrompt: "이 작품을 만들게 된 계기는 무엇인가요?",
  resultHelp: "제품 소개는 판매용 제목과 설명, 스토리는 다듬은 작가의 이야기, SNS는 짧은 게시글이에요. 사용할 언어를 고른 뒤 필요한 부분을 복사하세요.",

  typeHelp: "실제 형태에 맞는 종류를 골라주세요. 사진만으로 구분하기 어렵다면 ‘알 수 없음’을 유지하세요.",
  colorHelp: "배경과 그림자를 제외하고, 작품 자체의 색상을 최대 3개 골라주세요.",
  featureHelp: "실제 작품과 다른 특징은 ×로 지워주세요. 사진만으로 재료나 제작 기법을 확인할 수는 없어요.",
  productHelp: "상품명은 판매 페이지의 제목, 짧은 소개는 라벨이나 미리보기, 제품 설명은 상세 페이지에 사용하세요.",
  socialHelp: "인스타그램이나 페이스북에 붙여 넣을 짧은 소개글이에요. 게시 전에 작품 정보가 맞는지 확인하세요.",
  storyResultHelp: "입력한 원문과 다듬은 문장을 비교해보세요. 작업 계기나 경험이 원래 이야기와 같은지 확인해주세요.",
  cultureHelp: "선택한 문양에 관한 참고 정보예요. 이 작품의 제작 지역이나 시대를 증명하는 정보는 아니에요.",
  observationsTitle: "AI가 사진에서 관찰한 것",
  referencesTitle: "참고 자료(출처 있음)",
  noReference: "출처 있는 참고 자료가 아직 없습니다",
  descriptionLabel: "문양 설명", originLabel: "역사적 사례", worksLabel: "대표작 참고",
  shapeLabel: "전체 형태", surfaceLabel: "유약과 표면", layoutLabel: "장식 위치", elementsLabel: "장식 요소", compositionLabel: "문양 구성",
  observationLimit: "사진에 보이는 모습만 설명합니다. 시대·가마·원산지·진품 여부는 판단하지 않습니다. ‘not visible’은 사진에서 확인할 수 없다는 뜻입니다. 관찰 본문은 한국어·베트남어·영어로 바꿔 볼 수 있습니다.",
  confidenceLow: "AI 추정 · 확신 낮음",
  back: "이전 단계로",

  uploadHeading: "작품에 담긴 이야기를,\n더 많은 사람에게.",
  uploadHint: "제품 전체가 보이도록 밝은 곳에서 촬영해주세요.",
  takePhoto: "사진 촬영",
  chooseFromGallery: "갤러리에서 선택",
  retakePhoto: "다시 촬영",
  changePhoto: "사진 변경",
  startAnalysis: "AI 분석 시작",
  supportedFormats: "JPG · PNG · WEBP / HEIC는 브라우저에 따라 지원",
  unsupportedType: "JPG, PNG, WEBP, HEIC 형식의 사진만 사용할 수 있습니다.",
  imageDecodeFailed: "이 사진을 불러오지 못했습니다. 다른 사진을 선택해주세요.",
  preparingImage: "사진을 준비하고 있습니다...",
  uiLanguageToggle: "Tiếng Việt",

  analyzingTitle: "작품을 살펴보고 있어요.",
  analyzingBody: "제품 종류, 색상, 시각적 특징, 문양 후보를 분석하고 있습니다.",
  analyzeFailed: "사진을 분석하지 못했습니다.",
  chooseAnotherPhoto: "다른 사진 선택",

  observationHeading: "분석 결과",
  productType: "제품 종류",
  mainColors: "주요 색상",
  addColor: "+ 색상 선택",
  visualFeatures: "보이는 특징",
  removeItem: "삭제",
  noFeatures: "선택된 특징이 없습니다.",

  patternHeading: "어떤 문양인가요?",
  patternSelectHint: "문양을 하나 선택해주세요.",
  noPattern: "없음 / 알 수 없음",
  confidenceHigh: "AI 추정 · 일치 가능성 높음",
  confidenceMedium: "AI 추정 · 직접 확인 필요",
  allLowTitle: "확실한 문양 후보를 찾지 못했습니다.",
  noCandidatesTitle: "AI가 등록된 문양 중 일치하는 문양을 찾지 못했습니다.",
  showAllPatterns: "전체 문양 보기",
  patternDetail: "자세히",
  patternMeaningTitle: "문화적 의미",
  patternNoCulture: "검증된 문화 정보가 아직 등록되지 않았습니다.",
  patternSource: "출처",
  close: "닫기",
  continueConfirmed: "확인하고 계속",
  freeInputNotice:
    "검증된 목록에 있는 문양만 선택할 수 있습니다. 목록에 없으면 “없음 / 알 수 없음”을 선택해주세요.",

  storyHeading: "이 작품에 대해 들려주세요.",
  storyTabText: "직접 입력",
  storyTabVoice: "음성으로 말하기",
  storyPlaceholder:
    "예: “어릴 때 마을 연못에서 보았던 연꽃을 생각하면서 만든 작품입니다.”",
  storyTooLong: "1000자를 넘었습니다.",
  createContent: "콘텐츠 만들기",
  recordStart: "녹음 시작",
  recordMax: "최대 60초",
  recording: "녹음 중",
  recordStop: "녹음 끝내기",
  transcribing: "음성을 텍스트로 옮기고 있어요.",
  sttHeard: "AI가 이렇게 들었어요.",
  recordAgain: "다시 녹음",
  useThisText: "이 내용 사용",
  appendAfter: "뒤에 추가",
  replaceExisting: "기존 내용 바꾸기",
  cancel: "취소",
  micError: "이 브라우저에서는 음성 녹음이 제한될 수 있습니다.",
  micHelp: "인앱 브라우저 대신 Chrome이나 Safari에서 열어주세요.",
  micHelpButton: "브라우저에서 열기 안내",
  typeInstead: "직접 입력",
  sttFailed: "음성을 정확하게 인식하지 못했습니다.",
  voiceOptional: "음성 입력은 선택입니다. 직접 입력만으로도 콘텐츠를 만들 수 있습니다.",

  resultNoticeTitle: "작품 소개가 준비되었어요.",
  resultNoticeBody:
    "AI가 정리한 내용입니다. 복사하기 전에 사실과 표현을 확인해주세요.",
  tabProduct: "제품 소개",
  tabStory: "스토리",
  tabCulture: "문화",
  tabSocial: "SNS",
  storyOriginal: "장인의 원문",
  storyPolished: "AI가 정리한 이야기",
  storyEmpty: "장인이 입력한 이야기가 없습니다.",
  cultureFromDb: "Pattern Database에 기록된 내용입니다.",
  copy: "복사",
  copyAll: "전체 복사",
  copied: "✓ 복사됨",
  copyFailed: "자동 복사할 수 없습니다. 텍스트를 길게 눌러 복사해주세요.",
  generating: "작품의 이야기를 정리하고 있어요.",
  generateFailed: "콘텐츠를 만드는 중 문제가 발생했습니다.",
  retry: "다시 시도",
  editPattern: "문양 수정",
  editStory: "이야기 수정",
  regenerate: "다시 생성",
  apiKeyMissing: "현재 AI 서비스가 연결되지 않았어요. 잠시 후 다시 시도하거나 관리자에게 문의해주세요.",
};


const en: CopyDict = {
 studioLabel: "One product. One maker. One story.",
 uploadIntro: "Turn a photo and your own words into a story. Review it and share your piece with a QR code.",
 photoStep: "Photo", verifyStep: "Review", storyStep: "Story", resultStep: "Result",
 photoTitle: "Start with one piece", photoBody: "Choose a clear photo showing the whole shape and decoration against a simple background.",
 photoTips: "One piece · Good lighting · No filters", uploadNext: "Next, review and correct the features found by AI.", uploadingImage: "Uploading photo…",
 verifyIntro: "These are suggestions from the photo. Compare them with your piece and correct any mistakes below.",
 patternIntro: "AI suggests motifs from visible shapes. Select one you recognize, or choose ‘None / unknown’ if unsure.",
 storyIntro: "Share your inspiration, a memory, or a detail you want buyers to know. AI only edits the information you provide.",
 storyHelp: "You can leave this blank. The content will describe confirmed features without inventing a story.", storyPrompt: "What inspired you to make this piece?",
 resultHelp: "Choose a language, review the product description, story, or social post, then copy what you need.",
 typeHelp: "Choose the actual shape. Keep ‘Unknown’ if the photo is unclear.", colorHelp: "Choose up to 3 colors on the piece, excluding the background and shadows.",
 featureHelp: "Use × to remove incorrect features. A photo cannot confirm materials or manufacturing techniques.",
 productHelp: "Use the title for a listing, the short description for a label, and the full description for a product page.",
 socialHelp: "A short post for Facebook or Instagram. Check the facts before posting.", storyResultHelp: "Compare the original and edited versions. Inspiration and experiences must match your account.",
 cultureHelp: "Reference information about the motif; it does not establish this piece’s origin or age.",
 observationsTitle: "What AI observed in the photo", referencesTitle: "Sourced references", noReference: "No sourced reference material is available yet.",
 descriptionLabel: "Motif description", originLabel: "Historical context", worksLabel: "Reference works", shapeLabel: "Overall shape", surfaceLabel: "Surface and glaze", layoutLabel: "Decoration placement", elementsLabel: "Decorative elements", compositionLabel: "Composition",
 observationLimit: "Describes visible features only, without determining age, kiln, origin, or authenticity. ‘not visible’ means the photo does not show enough detail. Observations are available in Korean, Vietnamese, and English.", confidenceLow: "AI suggestion · Low confidence", back: "Back",
 uploadHeading: "Every piece,\na story to share.", uploadHint: "Take a well-lit photo showing the entire piece.", takePhoto: "Take a photo", chooseFromGallery: "Choose from gallery", retakePhoto: "Retake photo", changePhoto: "Change photo", startAnalysis: "Analyze photo", supportedFormats: "JPG · PNG · WEBP / HEIC support varies by browser", unsupportedType: "Choose a JPG, PNG, WEBP, or HEIC image.", imageDecodeFailed: "Could not read this image. Try another photo.", preparingImage: "Preparing photo…", uiLanguageToggle: "Language",
 analyzingTitle: "Looking at your piece.", analyzingBody: "Analyzing the shape, colors, visible features, and possible motifs.", analyzeFailed: "Could not analyze the photo.", chooseAnotherPhoto: "Choose another photo",
 observationHeading: "Analysis results", productType: "Product type", mainColors: "Main colors", addColor: "+ Add color", visualFeatures: "Visible features", removeItem: "Remove", noFeatures: "No features selected.",
 patternHeading: "Which motif is this?", patternSelectHint: "Select a motif to continue.", noPattern: "None / unknown", confidenceHigh: "AI suggestion · Likely match", confidenceMedium: "AI suggestion · Check the details", allLowTitle: "No confident motif match was found.", noCandidatesTitle: "AI found no matching motif in the registered list.", showAllPatterns: "Show all motifs", patternDetail: "Details", patternMeaningTitle: "Cultural meaning", patternNoCulture: "No verified cultural information is available yet.", patternSource: "Source", close: "Close", continueConfirmed: "Confirm and continue", freeInputNotice: "Choose from the registered list. If nothing matches, select ‘None / unknown’.",
 storyHeading: "Tell us about this piece.", storyTabText: "Type", storyTabVoice: "Record your voice", storyPlaceholder: "Example: I made this piece while remembering the lotus flowers in my childhood village pond.", storyTooLong: "The story exceeds 1,000 characters.", createContent: "Create content", recordStart: "Start recording", recordMax: "Up to 60 seconds", recording: "Recording", recordStop: "Stop recording", transcribing: "Transcribing your voice…", sttHeard: "Here is what AI heard.", recordAgain: "Record again", useThisText: "Use this text", appendAfter: "Add to the end", replaceExisting: "Replace existing text", cancel: "Cancel", micError: "Recording may be restricted in this browser.", micHelp: "Open this page in Chrome or Safari instead of an in-app browser.", micHelpButton: "How to open in a browser", typeInstead: "Type instead", sttFailed: "Could not transcribe the recording.", voiceOptional: "Voice input is optional. You can create content by typing.",
 resultNoticeTitle: "Your piece’s introduction is ready.", resultNoticeBody: "AI edited this content. Check the facts and wording before copying.", tabProduct: "Product", tabStory: "Story", tabCulture: "Culture", tabSocial: "Social", storyOriginal: "Artisan’s original words", storyPolished: "Story edited by AI", storyEmpty: "No artisan story was provided.", cultureFromDb: "From the sourced motif reference collection.", copy: "Copy", copyAll: "Copy all", copied: "✓ Copied", copyFailed: "Could not copy automatically. Select the text to copy it.", generating: "Preparing your piece’s story…", generateFailed: "Could not generate the content.", retry: "Try again", editPattern: "Edit motif", editStory: "Edit story", regenerate: "Regenerate", apiKeyMissing: "The AI service is unavailable. Try again later or contact the administrator.",
};

const COPY: Record<UiLanguage, CopyDict> = { vi, ko, en };

export function copyFor(language: UiLanguage): CopyDict {
  return COPY[language];
}
