import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { isPublicRequest, authenticated } from '../scripts/demo-gateway.mjs';
const root=await mkdtemp(join(tmpdir(),'craft-gateway-'));
const id='11111111-1111-4111-8111-111111111111';
assert.equal(await isPublicRequest('POST','/api/analyze-product',root),false);
assert.equal(await isPublicRequest('POST','/api/upload-image',root),false);
assert.equal(await isPublicRequest('POST','/api/transcribe',root),false);
assert.equal(await isPublicRequest('POST','/api/generate-content',root),false);
assert.equal(await isPublicRequest('PUT',`/api/exhibits/${id}`,root),false);
assert.equal(await isPublicRequest('GET',`/api/image/${id}`,root),false);
assert.equal(await isPublicRequest('GET',`/exhibit/${id}`,root),true);
await mkdir(join(root,'exhibits'));await writeFile(join(root,'exhibits','test.json'),JSON.stringify({imageId:id}));
assert.equal(await isPublicRequest('GET',`/api/image/${id}`,root),true);
assert(!authenticated({},'test-password'));
assert(!authenticated({authorization:'Basic '+Buffer.from('maker:wrong').toString('base64')},'test-password'));
assert(authenticated({authorization:'Basic '+Buffer.from('maker:test-password').toString('base64')},'test-password'));
console.log('PASS: private drafts and all paid/write endpoints require maker authentication; only published exhibit images public');
